config/routes.rb
Rails.application.routes.draw do
  resources :andamentos
  resources :produtos
  #devise_for :users
  get 'home/index'

  root to: "home#index"
  devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/andamento.rb
class Andamento < ApplicationRecord
  belongs_to :produto
  #has_many :produto

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :user
  has_many :andamentos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :admin, :inclusion => {in:[false],message: "você não esta autorizado"}, if: :primeiro_usuario?

          def primeiro_usuario?
            usuarios_cadastrados = User.all.count
            if usuarios_cadastrados == 0
              false
            else
              true
            end
          end




end

app/controllers/andamentos_controller.rb
class AndamentosController < ApplicationController
  before_action :set_andamento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /andamentos
  # GET /andamentos.json
  def index
    andamentos = []
    if current_user.admin === true
      @andamentos = Andamento.all
    else
      Andamento.all.each do |andamento|
        usuario = Produto.find(andamento.produto_id).user_id
         if current_user.id == usuario
           andamentos << andamento
         end
      end
      @andamentos = andamentos
    end
  end

  # GET /andamentos/1
  # GET /andamentos/1.json
  def show
  end

  # GET /andamentos/new
  def new
    @andamento = Andamento.new
  end

  # GET /andamentos/1/edit
  def edit
  end

  # POST /andamentos
  # POST /andamentos.json
  def create
    @andamento = Andamento.new(andamento_params)

    respond_to do |format|
      if @andamento.save
        format.html { redirect_to @andamento, notice: 'Andamento was successfully created.' }
        format.json { render :show, status: :created, location: @andamento }
      else
        format.html { render :new }
        format.json { render json: @andamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /andamentos/1
  # PATCH/PUT /andamentos/1.json
  def update
    respond_to do |format|
      if @andamento.update(andamento_params)
        format.html { redirect_to @andamento, notice: 'Andamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @andamento }
      else
        format.html { render :edit }
        format.json { render json: @andamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /andamentos/1
  # DELETE /andamentos/1.json
  def destroy
    @andamento.destroy
    respond_to do |format|
      format.html { redirect_to andamentos_url, notice: 'Andamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_andamento
      @andamento = Andamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def andamento_params
      p "==================================="
      p params
      p "==================================="
      params.require(:andamento).permit(:produto_id, :analisado, :consertado, :testado, :entregue, :data)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:user_id, :data, :objeto, :cpu, :hd, :memoria, :obs, :valor)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:admin,
                                                                 :nome,
                                                                 :telefone,
                                                                 :email,
                                                                 :password

      )}
  end
end

app/helpers/andamentos_helper.rb
module AndamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/andamentos/_form.html.erb
<%
  @col_produtos = []
  Produto.all.each do |produto|
    if !Andamento.exists?(produto_id: produto.id)
      @col_produtos << produto
    end
  end
%>
<%= simple_form_for(@andamento) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <% if action_name == "new" %>
      <%= f.association :produto, :collection => @col_produtos, label_method: :id, value_method: :id %>
    <% else %>
      <%= f.association :produto, label_method: :id, value_method: :id %>
    <% end %>
    <%= f.input :analisado %>
    <%= f.input :consertado  %>
    <%= f.input :testado  %>
    <%= f.input :entregue  %>
    <%= f.input :data  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/andamentos/edit.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>

          <h2>Editar Andamento</h2>

            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>
                <h3 style="height: 46px;">Área Restrita precisa logar...</h3>
                <p style="width: 294px;">


                  <table border="1"; align=center>
                      <tr>
                        <td align=right>


                          <%= render 'form', andamento: @andamento %>

                          <%= link_to 'Show', @andamento %> |
                          <%= link_to 'Back', andamentos_path %>





                        </td>
                        </tr>

                    </table>





                </p>
            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/andamentos/index.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>
          <h2>Andamento</h2>
            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>
                <p style="width: 294px;">
                <p id="notice"><%= notice %></p>





                  <table border="1"; align=center>
                    <thead>
                      <tr>
                        <th>Produto</th>
                        <th>Analisado</th>
                        <th>Consertado</th>
                        <th>Testado</th>
                        <th>Entregue</th>
                        <th>Data</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @andamentos.each do |andamento| %>
                        <tr>
                          <td><%= andamento.produto_id %></td>
                          <td><%= andamento.analisado %></td>
                          <td><%= andamento.consertado %></td>
                          <td><%= andamento.testado %></td>
                          <td><%= andamento.entregue %></td>
                          <td><%= andamento.data %></td>
                          <td><%= link_to 'Mostrar', andamento %></td>

                          <% if current_user.admin === true %>
                          <td><%= link_to 'Edit', edit_andamento_path(andamento) %></td>
                          <td><%= link_to 'Destroy', andamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <br>
                  <% if current_user.admin === true %>
                  <%= link_to 'New Andamento', new_andamento_path %>
                  <% end %>








                </p>

            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/andamentos/new.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>

          <h2>Novo Andamento</h2>

            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>
                <h3 style="height: 46px;">Área Restrita precisa logar...</h3>
                <p style="width: 294px;">


                  <table border="1"; align=center>
                      <tr>
                        <td align=right>



                          <%= render 'form', andamento: @andamento %>

                          <%= link_to 'Back', andamentos_path %>


                        </td>
                        </tr>

                    </table>





                </p>
            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/andamentos/show.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>
          <h2>Andamento</h2>
            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                </div>
                <p style="width: 294px;">




                <p id="notice"><%= notice %></p>

                  <p>
                    <h1>
                  <strong>Produto:</strong>
                  <%= @andamento.produto_id %>
                    </h1>
                </p>


                  <strong>Analisado:</strong>
                  <%= @andamento.analisado %>



                  <strong>Consertado:</strong>
                  <%= @andamento.consertado %>


                  <strong>Testado:</strong>
                  <%= @andamento.testado %>



                  <strong>Entregue:</strong>
                  <%= @andamento.entregue %>



                  <strong>Data:</strong>
                  <%= @andamento.data %>


                <%= link_to 'Edit', edit_andamento_path(@andamento) %> |
                <%= link_to 'Voltar', andamentos_path %>











                </p>

            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>



<html lang=”pt-br>
  <head>

    <!-- Código meu -->
    <meta charset="utf-8">



<!--

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style type="text/css">.tk-proxima-nova{font-family:"proxima-nova",sans-serif;}</style>
    <script src="javascripts/bootstrap.min.js"></script>
    <script src="javascripts/custom.js"></script>
    <script src="javascripts/gmaps.js"></script>
    <script src="javascripts/jquery-2.1.1.js"></script>
    <script src="javascripts/smoothscroll.js"></script>

    <link href="bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="style.css" rel="stylesheet" type="text/css"/>


-->








    <title>TecnoInfo</title>


    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>


    <!-- ============
    header section -->

    <header class="top-header">
      <div class="container">
        <div class="row">
          <div class="col-xs-5 header-logo">

            <br>

            <a href="/"><img src="<%= image_path('logo.png') %>" alt="" class="img-responsive logo"></a>
          </div>


          <div class="col-md-7">
            <nav class="navbar navbar-default">
              <div class="container-fluid nav-bar">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                  <ul class="nav navbar-nav navbar-right">
                    <li><a class="menu active" href="/">Home</a></li>
                    <li><a class="menu" href="/#about">Sobre</a></li>
                    <li><a class="menu" href="/#service">Serviços</a></li>
                    <li><a class="menu" href="/produtos">Produto</a></li>
                    <li><a class="menu" href="/andamentos">Andamento</a></li>

                    <% if user_signed_in? %>
                        <%= link_to "Sair   /", destroy_user_session_path, method: :delete %>
                        Logado como: <strong><%= current_user.email %></strong>

                    <%else%>
                    <%= link_to "Cadastrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
                    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                    <%end%>






                  </ul>

                </div><!-- /navbar-collapse -->
              </div><!-- / .container-fluid -->
            </nav>
          </div>
        </div>
      </div>
    </header> <!-- end of header area -->







<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    <%= yield %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>



<!-- footer starts here -->
<footer class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 footer-para">
        <p>&copy; <a href="https://www.freshdesignweb.com">tecnoinfo.com</a> All right reserved</p>
      </div>

      <div class="col-xs-6 text-right">
        <a href=""><i class="fa fa-facebook"></i></a>
        <a href=""><i class="fa fa-twitter"></i></a>
        <a href=""><i class="fa fa-skype"></i></a>
      </div>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/produtos/_form.html.erb
<%= simple_form_for(@produto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user, value_method: :id, label_method: :nome %>
    <%= f.input :data %>
    <%= f.input :objeto %>
    <%= f.input :cpu %>
    <%= f.input :hd %>
    <%= f.input :memoria %>
    <%= f.input :obs %>
    <%= f.input :valor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>

          <h2>Editar Produto</h2>

            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>
                <h3 style="height: 46px;">Área Restrita precisa logar...</h3>
                <p style="width: 294px;">


                  <table border="1"; align=center>
                      <tr>
                        <td align=right>



                          <%= render 'form', produto: @produto %>

                          <%= link_to 'Show', @produto %> |
                          <%= link_to 'Back', produtos_path %>



                        </td>
                        </tr>

                    </table>





                </p>
            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/produtos/index.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>
          <h2>Produtos</h2>

            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>

                <p style="width: 294px;">

                  <p id="notice"><%= notice %></p>



                  <table border="1"; align=center>
                    <thead>
                      <tr>

                        <th>User</th>
                        <th>Id</th>
                        <th>Data</th>
                        <th>Objeto</th>
                        <th>Cpu</th>
                        <th>Hd</th>
                        <th>Memoria</th>
                        <th>Obs</th>
                        <th>Valor</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>

                      <% @produtos.each do |produto| %>
                        <tr>
                          <% if produto.user_id == current_user.id || current_user.admin === true %>
                          <td><%= produto.user.nome %></td>
                          <td><%= produto.id %></td>
                          <td><%= produto.data %></td>
                          <td><%= produto.objeto %></td>
                          <td><%= produto.cpu %></td>
                          <td><%= produto.hd %></td>
                          <td><%= produto.memoria %></td>
                          <td><%= produto.obs %></td>
                          <td><%= produto.valor %></td>


                          <td><%= link_to 'Mostrar', andamentos_path + "/" + produto.id.to_s %></td>


                          <% if current_user.admin === true %>
                          <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
                          <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          <% end %>


                          <% end %>

                        </tr>
                      <% end %>
                    </tbody>
                  </table>

                  <br>
                  <% if current_user.admin === true %>
                    <%= link_to 'New Produto', new_produto_path %>
                  <% end %>







                </p>

            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/produtos/new.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>

          <h2>Novo Produto</h2>

            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>
                <h3 style="height: 46px;">Área Restrita precisa logar...</h3>
                <p style="width: 294px;">


                  <table border="1"; align=center>
                      <tr>
                        <td align=right>
                          <%= render 'form', produto: @produto %>

                          <%= link_to 'Back', produtos_path %>

                        </td>
                        </tr>

                    </table>





                </p>
            </div>
          </div>

          </div>
        </div>
      </div>
    </section>

app/views/produtos/show.html.erb
<section class="about text-center" id="about">
      <div class="container">
        <div class="row">
          <br>
          <br>
          <br>

          <h2>Novo Produto</h2>

            <div class="single-about-detail clearfix">
              <div class="about-img"> <br>
              </div>
              <div class="about-details">
                <div class="pentagon-text">
                  <h1></h1>
                </div>
                <h3 style="height: 46px;">Área Restrita precisa logar...</h3>
                <p style="width: 294px;">


                  <table border="1"; align=center>
                      <tr>
                        <td align=right>

                          <p id="notice"><%= notice %></p>
<h1>
                          <p>
                            <strong>User:</strong>
                            <%= @produto.user.nome %>
                          </p>

                          <p>
                            <strong>Data:</strong>
                            <%= @produto.data %>
                          </p>

                          <p>
                            <strong>Objeto:</strong>
                            <%= @produto.objeto %>
                          </p>

                          <p>
                            <strong>Cpu:</strong>
                            <%= @produto.cpu %>
                          </p>

                          <p>
                            <strong>Hd:</strong>
                            <%= @produto.hd %>
                          </p>

                          <p>
                            <strong>Memoria:</strong>
                            <%= @produto.memoria %>
                          </p>

                          <p>
                            <strong>Obs:</strong>
                            <%= @produto.obs %>
                          </p>

                          <p>
                            <strong>Valor:</strong>
                            <%= @produto.valor %>
                          </p>

                          <%= link_to 'Edit', edit_produto_path(@produto) %> |
                          <%= link_to 'Back', produtos_path %>

</h1>

                        </td>
                        </tr>

                    </table>





                </p>
            </div>
          </div>

          </div>
        </div>
      </div>
    </section>